name: Esporta PDF
on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm install
      - run: node esporta.js
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: cheatsheet
          path: cheatsheet.pdf 